language: java

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
  - sudo apt-get install -y dpkg  ## to upgrade to dpkg >= 1.17.5ubuntu5.8, which fixes https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
  
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  
cache:
  directories:
  - "$HOME/.m2"

script:
  - mvn test -B -DskipDockerTests=true -P reportCoverage

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x frontend/scripts/deploy-npm.sh && sh frontend/scripts/deploy-npm.sh
    on:
      tags: true
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery-dev
    on:
      branch: develop
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery
    on:
      branch: master
